# Custom Language File for Launcher Customizer

[ejs.app]
title = "Orezia Launcher"

[ejs.landing]
mediaGitHubURL = "https://oreziamc.fr"
mediaTwitterURL = "https://x.com/OreziaMC"
mediaInstagramURL = "https://www.instagram.com/oreziamc/"
mediaDiscordURL = "https://discord.oreziamc.fr"

[ejs.settings]
sourceGithubLink = "https://github.com/Orezia/Orezia-Launcher"
supportLink = "https://discord.oreziamc.fr"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Orezia"
welcomeDescription = "Serveurs Minecraft 1.21 - Evoluer, farmer, construire, commercer, explorer ! Venez écrire votre histoire sur Orezia !"
welcomeDescCTA = "Tu n'es plus qu'à quelques clics d'Orezia !"
